language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  - FLASK=0.8
  - FLASK=0.9
  - FLASK=0.10
install:
  - pip install Flask==$FLASK
  - pip install -r requirements-dev.pip
script:
  - nosetests tests
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master
